// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"lizobly/ctc-db-api/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTravellerRepository creates a new instance of MockTravellerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTravellerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTravellerRepository {
	mock := &MockTravellerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTravellerRepository is an autogenerated mock type for the TravellerRepository type
type MockTravellerRepository struct {
	mock.Mock
}

type MockTravellerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTravellerRepository) EXPECT() *MockTravellerRepository_Expecter {
	return &MockTravellerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Create(ctx context.Context, input *domain.Traveller) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Traveller) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTravellerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Traveller
func (_e *MockTravellerRepository_Expecter) Create(ctx interface{}, input interface{}) *MockTravellerRepository_Create_Call {
	return &MockTravellerRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockTravellerRepository_Create_Call) Run(run func(ctx context.Context, input *domain.Traveller)) *MockTravellerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Traveller
		if args[1] != nil {
			arg1 = args[1].(*domain.Traveller)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Create_Call) Return(err error) *MockTravellerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input *domain.Traveller) error) *MockTravellerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTravellerWithAccessory provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) CreateTravellerWithAccessory(ctx context.Context, traveller *domain.Traveller, accessory *domain.Accessory) error {
	ret := _mock.Called(ctx, traveller, accessory)

	if len(ret) == 0 {
		panic("no return value specified for CreateTravellerWithAccessory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Traveller, *domain.Accessory) error); ok {
		r0 = returnFunc(ctx, traveller, accessory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_CreateTravellerWithAccessory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTravellerWithAccessory'
type MockTravellerRepository_CreateTravellerWithAccessory_Call struct {
	*mock.Call
}

// CreateTravellerWithAccessory is a helper method to define mock.On call
//   - ctx context.Context
//   - traveller *domain.Traveller
//   - accessory *domain.Accessory
func (_e *MockTravellerRepository_Expecter) CreateTravellerWithAccessory(ctx interface{}, traveller interface{}, accessory interface{}) *MockTravellerRepository_CreateTravellerWithAccessory_Call {
	return &MockTravellerRepository_CreateTravellerWithAccessory_Call{Call: _e.mock.On("CreateTravellerWithAccessory", ctx, traveller, accessory)}
}

func (_c *MockTravellerRepository_CreateTravellerWithAccessory_Call) Run(run func(ctx context.Context, traveller *domain.Traveller, accessory *domain.Accessory)) *MockTravellerRepository_CreateTravellerWithAccessory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Traveller
		if args[1] != nil {
			arg1 = args[1].(*domain.Traveller)
		}
		var arg2 *domain.Accessory
		if args[2] != nil {
			arg2 = args[2].(*domain.Accessory)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_CreateTravellerWithAccessory_Call) Return(err error) *MockTravellerRepository_CreateTravellerWithAccessory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_CreateTravellerWithAccessory_Call) RunAndReturn(run func(ctx context.Context, traveller *domain.Traveller, accessory *domain.Accessory) error) *MockTravellerRepository_CreateTravellerWithAccessory_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTravellerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTravellerRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTravellerRepository_Delete_Call {
	return &MockTravellerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTravellerRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTravellerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Delete_Call) Return(err error) *MockTravellerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockTravellerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) GetByID(ctx context.Context, id int) (domain.Traveller, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Traveller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Traveller, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Traveller); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Traveller)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTravellerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTravellerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTravellerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTravellerRepository_GetByID_Call {
	return &MockTravellerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTravellerRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockTravellerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_GetByID_Call) Return(result domain.Traveller, err error) *MockTravellerRepository_GetByID_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockTravellerRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Traveller, error)) *MockTravellerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) GetList(ctx context.Context, filter domain.ListTravellerRequest, offset int, limit int) ([]domain.Traveller, int64, error) {
	ret := _mock.Called(ctx, filter, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []domain.Traveller
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListTravellerRequest, int, int) ([]domain.Traveller, int64, error)); ok {
		return returnFunc(ctx, filter, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListTravellerRequest, int, int) []domain.Traveller); ok {
		r0 = returnFunc(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Traveller)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListTravellerRequest, int, int) int64); ok {
		r1 = returnFunc(ctx, filter, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.ListTravellerRequest, int, int) error); ok {
		r2 = returnFunc(ctx, filter, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTravellerRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockTravellerRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ListTravellerRequest
//   - offset int
//   - limit int
func (_e *MockTravellerRepository_Expecter) GetList(ctx interface{}, filter interface{}, offset interface{}, limit interface{}) *MockTravellerRepository_GetList_Call {
	return &MockTravellerRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, filter, offset, limit)}
}

func (_c *MockTravellerRepository_GetList_Call) Run(run func(ctx context.Context, filter domain.ListTravellerRequest, offset int, limit int)) *MockTravellerRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListTravellerRequest
		if args[1] != nil {
			arg1 = args[1].(domain.ListTravellerRequest)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_GetList_Call) Return(result []domain.Traveller, total int64, err error) *MockTravellerRepository_GetList_Call {
	_c.Call.Return(result, total, err)
	return _c
}

func (_c *MockTravellerRepository_GetList_Call) RunAndReturn(run func(ctx context.Context, filter domain.ListTravellerRequest, offset int, limit int) ([]domain.Traveller, int64, error)) *MockTravellerRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Update(ctx context.Context, input *domain.Traveller) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Traveller) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTravellerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Traveller
func (_e *MockTravellerRepository_Expecter) Update(ctx interface{}, input interface{}) *MockTravellerRepository_Update_Call {
	return &MockTravellerRepository_Update_Call{Call: _e.mock.On("Update", ctx, input)}
}

func (_c *MockTravellerRepository_Update_Call) Run(run func(ctx context.Context, input *domain.Traveller)) *MockTravellerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Traveller
		if args[1] != nil {
			arg1 = args[1].(*domain.Traveller)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Update_Call) Return(err error) *MockTravellerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, input *domain.Traveller) error) *MockTravellerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTravellerWithAccessory provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) UpdateTravellerWithAccessory(ctx context.Context, id int, traveller *domain.Traveller, accessory *domain.Accessory) error {
	ret := _mock.Called(ctx, id, traveller, accessory)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTravellerWithAccessory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *domain.Traveller, *domain.Accessory) error); ok {
		r0 = returnFunc(ctx, id, traveller, accessory)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_UpdateTravellerWithAccessory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTravellerWithAccessory'
type MockTravellerRepository_UpdateTravellerWithAccessory_Call struct {
	*mock.Call
}

// UpdateTravellerWithAccessory is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - traveller *domain.Traveller
//   - accessory *domain.Accessory
func (_e *MockTravellerRepository_Expecter) UpdateTravellerWithAccessory(ctx interface{}, id interface{}, traveller interface{}, accessory interface{}) *MockTravellerRepository_UpdateTravellerWithAccessory_Call {
	return &MockTravellerRepository_UpdateTravellerWithAccessory_Call{Call: _e.mock.On("UpdateTravellerWithAccessory", ctx, id, traveller, accessory)}
}

func (_c *MockTravellerRepository_UpdateTravellerWithAccessory_Call) Run(run func(ctx context.Context, id int, traveller *domain.Traveller, accessory *domain.Accessory)) *MockTravellerRepository_UpdateTravellerWithAccessory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *domain.Traveller
		if args[2] != nil {
			arg2 = args[2].(*domain.Traveller)
		}
		var arg3 *domain.Accessory
		if args[3] != nil {
			arg3 = args[3].(*domain.Accessory)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_UpdateTravellerWithAccessory_Call) Return(err error) *MockTravellerRepository_UpdateTravellerWithAccessory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_UpdateTravellerWithAccessory_Call) RunAndReturn(run func(ctx context.Context, id int, traveller *domain.Traveller, accessory *domain.Accessory) error) *MockTravellerRepository_UpdateTravellerWithAccessory_Call {
	_c.Call.Return(run)
	return _c
}
