all: false
dir: '{{.InterfaceDir}}/mocks'
filename: "{{.InterfaceName}}Mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  lizobly/ctc-db-api/traveller:
    config:
      all: true
  lizobly/ctc-db-api/user:
    config:
      all: true
  lizobly/ctc-db-api/internal/rest:
    config:
      all: true
