// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"lizobly/ctc-db-api/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessoryRepository creates a new instance of MockAccessoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessoryRepository {
	mock := &MockAccessoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessoryRepository is an autogenerated mock type for the AccessoryRepository type
type MockAccessoryRepository struct {
	mock.Mock
}

type MockAccessoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessoryRepository) EXPECT() *MockAccessoryRepository_Expecter {
	return &MockAccessoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccessoryRepository
func (_mock *MockAccessoryRepository) Create(ctx context.Context, input *domain.Accessory) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Accessory) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccessoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Accessory
func (_e *MockAccessoryRepository_Expecter) Create(ctx interface{}, input interface{}) *MockAccessoryRepository_Create_Call {
	return &MockAccessoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockAccessoryRepository_Create_Call) Run(run func(ctx context.Context, input *domain.Accessory)) *MockAccessoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Accessory
		if args[1] != nil {
			arg1 = args[1].(*domain.Accessory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessoryRepository_Create_Call) Return(err error) *MockAccessoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input *domain.Accessory) error) *MockAccessoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function for the type MockAccessoryRepository
func (_mock *MockAccessoryRepository) GetList(ctx context.Context, filter domain.ListAccessoryRequest, offset int, limit int) ([]domain.Accessory, map[int64]string, int64, error) {
	ret := _mock.Called(ctx, filter, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []domain.Accessory
	var r1 map[int64]string
	var r2 int64
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListAccessoryRequest, int, int) ([]domain.Accessory, map[int64]string, int64, error)); ok {
		return returnFunc(ctx, filter, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ListAccessoryRequest, int, int) []domain.Accessory); ok {
		r0 = returnFunc(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Accessory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ListAccessoryRequest, int, int) map[int64]string); ok {
		r1 = returnFunc(ctx, filter, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[int64]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.ListAccessoryRequest, int, int) int64); ok {
		r2 = returnFunc(ctx, filter, offset, limit)
	} else {
		r2 = ret.Get(2).(int64)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, domain.ListAccessoryRequest, int, int) error); ok {
		r3 = returnFunc(ctx, filter, offset, limit)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockAccessoryRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockAccessoryRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ListAccessoryRequest
//   - offset int
//   - limit int
func (_e *MockAccessoryRepository_Expecter) GetList(ctx interface{}, filter interface{}, offset interface{}, limit interface{}) *MockAccessoryRepository_GetList_Call {
	return &MockAccessoryRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, filter, offset, limit)}
}

func (_c *MockAccessoryRepository_GetList_Call) Run(run func(ctx context.Context, filter domain.ListAccessoryRequest, offset int, limit int)) *MockAccessoryRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ListAccessoryRequest
		if args[1] != nil {
			arg1 = args[1].(domain.ListAccessoryRequest)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccessoryRepository_GetList_Call) Return(result []domain.Accessory, ownerNames map[int64]string, total int64, err error) *MockAccessoryRepository_GetList_Call {
	_c.Call.Return(result, ownerNames, total, err)
	return _c
}

func (_c *MockAccessoryRepository_GetList_Call) RunAndReturn(run func(ctx context.Context, filter domain.ListAccessoryRequest, offset int, limit int) ([]domain.Accessory, map[int64]string, int64, error)) *MockAccessoryRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAccessoryRepository
func (_mock *MockAccessoryRepository) Update(ctx context.Context, input *domain.Accessory) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Accessory) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccessoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Accessory
func (_e *MockAccessoryRepository_Expecter) Update(ctx interface{}, input interface{}) *MockAccessoryRepository_Update_Call {
	return &MockAccessoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, input)}
}

func (_c *MockAccessoryRepository_Update_Call) Run(run func(ctx context.Context, input *domain.Accessory)) *MockAccessoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Accessory
		if args[1] != nil {
			arg1 = args[1].(*domain.Accessory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessoryRepository_Update_Call) Return(err error) *MockAccessoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessoryRepository_Update_Call) RunAndReturn(run func(ctx context.Context, input *domain.Accessory) error) *MockAccessoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
