// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"lizobly/ctc-db-api/pkg/domain"
	"lizobly/ctc-db-api/pkg/helpers"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessoryService creates a new instance of MockAccessoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessoryService {
	mock := &MockAccessoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessoryService is an autogenerated mock type for the AccessoryService type
type MockAccessoryService struct {
	mock.Mock
}

// GetList provides a mock function with given fields: ctx, filter, params
func (_m *MockAccessoryService) GetList(ctx context.Context, filter domain.ListAccessoryRequest, params helpers.PaginationParams) (helpers.PaginatedResponse[domain.AccessoryListItemResponse], error) {
	ret := _m.Called(ctx, filter, params)
	var r0 helpers.PaginatedResponse[domain.AccessoryListItemResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListAccessoryRequest, helpers.PaginationParams) (helpers.PaginatedResponse[domain.AccessoryListItemResponse], error)); ok {
		return rf(ctx, filter, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListAccessoryRequest, helpers.PaginationParams) helpers.PaginatedResponse[domain.AccessoryListItemResponse]); ok {
		r0 = rf(ctx, filter, params)
	} else {
		r0 = ret.Get(0).(helpers.PaginatedResponse[domain.AccessoryListItemResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListAccessoryRequest, helpers.PaginationParams) error); ok {
		r1 = rf(ctx, filter, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
