// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"lizobly/ctc-db-api/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccessoryRepository creates a new instance of MockAccessoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessoryRepository {
	mock := &MockAccessoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccessoryRepository is an autogenerated mock type for the AccessoryRepository type
type MockAccessoryRepository struct {
	mock.Mock
}

type MockAccessoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessoryRepository) EXPECT() *MockAccessoryRepository_Expecter {
	return &MockAccessoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccessoryRepository
func (_mock *MockAccessoryRepository) Create(ctx context.Context, input *domain.Accessory) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Accessory) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccessoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccessoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Accessory
func (_e *MockAccessoryRepository_Expecter) Create(ctx interface{}, input interface{}) *MockAccessoryRepository_Create_Call {
	return &MockAccessoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockAccessoryRepository_Create_Call) Run(run func(ctx context.Context, input *domain.Accessory)) *MockAccessoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Accessory
		if args[1] != nil {
			arg1 = args[1].(*domain.Accessory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccessoryRepository_Create_Call) Return(err error) *MockAccessoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccessoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input *domain.Accessory) error) *MockAccessoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
