// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"lizobly/ctc-db-api/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTravellerRepository creates a new instance of MockTravellerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTravellerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTravellerRepository {
	mock := &MockTravellerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTravellerRepository is an autogenerated mock type for the TravellerRepository type
type MockTravellerRepository struct {
	mock.Mock
}

type MockTravellerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTravellerRepository) EXPECT() *MockTravellerRepository_Expecter {
	return &MockTravellerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Create(ctx context.Context, input *domain.Traveller) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Traveller) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTravellerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Traveller
func (_e *MockTravellerRepository_Expecter) Create(ctx interface{}, input interface{}) *MockTravellerRepository_Create_Call {
	return &MockTravellerRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockTravellerRepository_Create_Call) Run(run func(ctx context.Context, input *domain.Traveller)) *MockTravellerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Traveller
		if args[1] != nil {
			arg1 = args[1].(*domain.Traveller)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Create_Call) Return(err error) *MockTravellerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input *domain.Traveller) error) *MockTravellerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTravellerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTravellerRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTravellerRepository_Delete_Call {
	return &MockTravellerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTravellerRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTravellerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Delete_Call) Return(err error) *MockTravellerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockTravellerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) GetByID(ctx context.Context, id int) (domain.Traveller, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Traveller
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Traveller, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Traveller); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Traveller)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTravellerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTravellerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTravellerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTravellerRepository_GetByID_Call {
	return &MockTravellerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTravellerRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockTravellerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_GetByID_Call) Return(result domain.Traveller, err error) *MockTravellerRepository_GetByID_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockTravellerRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Traveller, error)) *MockTravellerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTravellerRepository
func (_mock *MockTravellerRepository) Update(ctx context.Context, input *domain.Traveller) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Traveller) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTravellerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTravellerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.Traveller
func (_e *MockTravellerRepository_Expecter) Update(ctx interface{}, input interface{}) *MockTravellerRepository_Update_Call {
	return &MockTravellerRepository_Update_Call{Call: _e.mock.On("Update", ctx, input)}
}

func (_c *MockTravellerRepository_Update_Call) Run(run func(ctx context.Context, input *domain.Traveller)) *MockTravellerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Traveller
		if args[1] != nil {
			arg1 = args[1].(*domain.Traveller)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTravellerRepository_Update_Call) Return(err error) *MockTravellerRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTravellerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, input *domain.Traveller) error) *MockTravellerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
